name: CI - Monitoramento de Temperatura

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Instalar dependências do sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip python3-setuptools build-essential
        sudo apt-get install -y libffi-dev libssl-dev

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Rodar script de monitoramento
      run: |
        python monitoramento.py
