name: CI - Monitoramento de Temperatura

on:
  push:
    branches:
      - main  # Quando houver um push para o branch principal
  pull_request:
    branches:
      - main  # Quando um pull request for criado para o branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # Define que o ambiente será Ubuntu

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Defina a versão do Python que você está usando no seu projeto

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt  # Certifique-se de que você tem um arquivo requirements.txt com Adafruit_DHT e outras dependências

    - name: Rodar script de monitoramento
      run: |
        python monitoramento.py  # Altere para o nome do seu script Python
